### ISSUE TITLE
Release fails when using this task

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [mvdiemen/XLDeployRelease-VstsTask#1]
After adding the task, the release fails after the download artifact step. It doesn't matter where the XLD step is. When we take it out of the release, the release runs fine again.
Using TFS 2015.3 on premise.

2017-01-19T08:07:47.4671730Z ##[error]Can not add property defaultValue to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.

**Comment by maartenvandiemen** [comment]
@thijsvanbloemendaal do you mean when you disable the download artifact everything runs fine? Or isn't the activity working at all?

**Comment by maartenvandiemen** [comment]
@thijsvanbloemendaal or are you using the activity multiple times in one release definition?

**Comment by thijsvanbloemendaal** [comment]
As soon as I add 1 task it stops working..
I'll check this week to make sure I'm ding the latest version.

**Comment by maartenvandiemen** [comment]
@thijsvanbloemendaal I will reproduce the issue and provide a fix before next Monday.

**Comment by thijsvanbloemendaal** [comment]
Thanks, let me know if I can help.

**Comment by maartenvandiemen** [comment]
@thijsvanbloemendaal Fixed in 1.0.2.
